# Generated by Django 4.2.5 on 2024-03-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_transaction_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="cart",
        ),
    ]
