# Generated by Django 4.2.5 on 2024-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_transaction_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
