# Generated by Django 4.2.5 on 2024-03-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="cart_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cartitem",
            ),
        ),
    ]
