# Generated by Django 4.2.5 on 2024-03-24 06:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="webp_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
