# Generated by Django 4.2.5 on 2024-03-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0003_alter_photo_tags_alter_photo_webp_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="photo.tag"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="webp_image",
            field=models.URLField(blank=True, default="#"),
            preserve_default=False,
        ),
    ]
