# Generated by Django 4.2.5 on 2024-03-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photo_tags_alter_photo_webp_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='webp_image',
            new_name='watermarked_image',
        ),
    ]
