# Generated by Django 4.2.5 on 2024-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_watermarked_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='watermarked_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='webp_image',
            field=models.URLField(blank=True),
        ),
    ]
