# Generated by Django 4.2.5 on 2024-03-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_photo_approved_photo_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
    ]
