# Generated by Django 4.2.5 on 2024-03-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
